export type EmployeeStatus = 'Active' | 'Remote' | 'On Leave' | 'Probation'

export type EmployeeRecord = {
  id: string
  name: string
  department: 'Engineering' | 'Human Resources' | 'Finance' | 'Design' | 'Operations' | 'Sales'
  role: string
  manager: string
  status: EmployeeStatus
  joinDate: string
  location: 'New York, USA' | 'Austin, USA' | 'Chicago, USA' | 'London, UK' | 'Toronto, Canada'
  email: string
  phone: string
  emergencyContact: string
  employmentType: 'Full-time' | 'Contract'
  salaryBand: string
  attendanceRate: string
  leavesTaken: string
  performanceScore: string
}

export const employees: EmployeeRecord[] = [
  {
    id: 'EMP-1048',
    name: 'Olivia Bennett',
    department: 'Engineering',
    role: 'Senior Frontend Engineer',
    manager: 'Marcus Hill',
    status: 'Active',
    joinDate: '2022-03-14',
    location: 'New York, USA',
    email: 'olivia.bennett@acmehr.com',
    phone: '+1 (212) 555-0148',
    emergencyContact: 'Mason Bennett · +1 (212) 555-0191',
    employmentType: 'Full-time',
    salaryBand: 'B4',
    attendanceRate: '97.2%',
    leavesTaken: '06',
    performanceScore: '4.8/5',
  },
  {
    id: 'EMP-1052',
    name: 'Daniel Kim',
    department: 'Finance',
    role: 'Financial Analyst',
    manager: 'Priya Shah',
    status: 'Remote',
    joinDate: '2021-09-06',
    location: 'Toronto, Canada',
    email: 'daniel.kim@acmehr.com',
    phone: '+1 (416) 555-0152',
    emergencyContact: 'Mina Kim · +1 (416) 555-0170',
    employmentType: 'Full-time',
    salaryBand: 'B3',
    attendanceRate: '94.8%',
    leavesTaken: '04',
    performanceScore: '4.4/5',
  },
  {
    id: 'EMP-1061',
    name: 'Ava Thompson',
    department: 'Human Resources',
    role: 'HR Business Partner',
    manager: 'Leah Morgan',
    status: 'Active',
    joinDate: '2023-01-23',
    location: 'Chicago, USA',
    email: 'ava.thompson@acmehr.com',
    phone: '+1 (312) 555-0161',
    emergencyContact: 'Ryan Thompson · +1 (312) 555-0188',
    employmentType: 'Full-time',
    salaryBand: 'B3',
    attendanceRate: '96.1%',
    leavesTaken: '05',
    performanceScore: '4.6/5',
  },
  {
    id: 'EMP-1067',
    name: 'Ethan Carter',
    department: 'Operations',
    role: 'Operations Coordinator',
    manager: 'Monica Reyes',
    status: 'Probation',
    joinDate: '2024-11-04',
    location: 'Austin, USA',
    email: 'ethan.carter@acmehr.com',
    phone: '+1 (512) 555-0167',
    emergencyContact: 'Ariana Carter · +1 (512) 555-0113',
    employmentType: 'Full-time',
    salaryBand: 'B2',
    attendanceRate: '92.5%',
    leavesTaken: '01',
    performanceScore: '4.1/5',
  },
  {
    id: 'EMP-1074',
    name: 'Sophia Martinez',
    department: 'Design',
    role: 'Product Designer',
    manager: 'Nina Walker',
    status: 'Remote',
    joinDate: '2022-07-18',
    location: 'London, UK',
    email: 'sophia.martinez@acmehr.com',
    phone: '+44 20 7946 1074',
    emergencyContact: 'Luis Martinez · +44 20 7946 1180',
    employmentType: 'Full-time',
    salaryBand: 'B3',
    attendanceRate: '95.9%',
    leavesTaken: '07',
    performanceScore: '4.7/5',
  },
  {
    id: 'EMP-1083',
    name: 'Noah Patel',
    department: 'Engineering',
    role: 'Backend Engineer',
    manager: 'Marcus Hill',
    status: 'Active',
    joinDate: '2020-05-11',
    location: 'Austin, USA',
    email: 'noah.patel@acmehr.com',
    phone: '+1 (512) 555-0183',
    emergencyContact: 'Priya Patel · +1 (512) 555-0176',
    employmentType: 'Full-time',
    salaryBand: 'B4',
    attendanceRate: '98.4%',
    leavesTaken: '03',
    performanceScore: '4.9/5',
  },
  {
    id: 'EMP-1090',
    name: 'Grace Liu',
    department: 'Sales',
    role: 'Account Executive',
    manager: 'Trevor Miles',
    status: 'On Leave',
    joinDate: '2021-11-29',
    location: 'New York, USA',
    email: 'grace.liu@acmehr.com',
    phone: '+1 (646) 555-0190',
    emergencyContact: 'Kevin Liu · +1 (646) 555-0181',
    employmentType: 'Full-time',
    salaryBand: 'B3',
    attendanceRate: '93.7%',
    leavesTaken: '09',
    performanceScore: '4.3/5',
  },
  {
    id: 'EMP-1098',
    name: 'Liam Foster',
    department: 'Operations',
    role: 'Facilities Lead',
    manager: 'Monica Reyes',
    status: 'Active',
    joinDate: '2019-08-12',
    location: 'Chicago, USA',
    email: 'liam.foster@acmehr.com',
    phone: '+1 (312) 555-0198',
    emergencyContact: 'Emma Foster · +1 (312) 555-0156',
    employmentType: 'Full-time',
    salaryBand: 'B3',
    attendanceRate: '97.8%',
    leavesTaken: '04',
    performanceScore: '4.5/5',
  },
  {
    id: 'EMP-1106',
    name: 'Charlotte Reed',
    department: 'Human Resources',
    role: 'Talent Acquisition Specialist',
    manager: 'Leah Morgan',
    status: 'Active',
    joinDate: '2023-04-17',
    location: 'Toronto, Canada',
    email: 'charlotte.reed@acmehr.com',
    phone: '+1 (416) 555-0106',
    emergencyContact: 'Mila Reed · +1 (416) 555-0174',
    employmentType: 'Full-time',
    salaryBand: 'B2',
    attendanceRate: '96.8%',
    leavesTaken: '02',
    performanceScore: '4.5/5',
  },
  {
    id: 'EMP-1115',
    name: 'James Walker',
    department: 'Finance',
    role: 'Payroll Manager',
    manager: 'Priya Shah',
    status: 'Remote',
    joinDate: '2020-10-08',
    location: 'London, UK',
    email: 'james.walker@acmehr.com',
    phone: '+44 20 7946 1115',
    emergencyContact: 'Lena Walker · +44 20 7946 1162',
    employmentType: 'Full-time',
    salaryBand: 'B4',
    attendanceRate: '95.1%',
    leavesTaken: '05',
    performanceScore: '4.6/5',
  },
  {
    id: 'EMP-1124',
    name: 'Mia Gonzalez',
    department: 'Sales',
    role: 'Sales Operations Analyst',
    manager: 'Trevor Miles',
    status: 'Active',
    joinDate: '2022-02-21',
    location: 'Austin, USA',
    email: 'mia.gonzalez@acmehr.com',
    phone: '+1 (512) 555-0124',
    emergencyContact: 'Rosa Gonzalez · +1 (512) 555-0178',
    employmentType: 'Full-time',
    salaryBand: 'B2',
    attendanceRate: '97.1%',
    leavesTaken: '03',
    performanceScore: '4.4/5',
  },
  {
    id: 'EMP-1138',
    name: 'Benjamin Clark',
    department: 'Engineering',
    role: 'QA Automation Engineer',
    manager: 'Marcus Hill',
    status: 'Probation',
    joinDate: '2025-01-13',
    location: 'New York, USA',
    email: 'benjamin.clark@acmehr.com',
    phone: '+1 (212) 555-0138',
    emergencyContact: 'Julia Clark · +1 (212) 555-0143',
    employmentType: 'Full-time',
    salaryBand: 'B2',
    attendanceRate: '91.9%',
    leavesTaken: '00',
    performanceScore: '4.0/5',
  },
]

export function getEmployeeById(id: string) {
  return employees.find((employee) => employee.id === id)
}

export function getEmployeeInitials(name: string) {
  return name
    .split(' ')
    .map((part) => part[0])
    .join('')
    .slice(0, 2)
    .toUpperCase()
}
